services:
  restauranteapi:
    build:
      context: .
      dockerfile: DockerfileAPI
    restart: always
    depends_on:
      - dbrestauranteapi
    ports:
      - "8080:8080"
    environment:
      CONTAINER: "dbrestauranteapi"
      DB_NAME: ${DB_NAME}
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}
      RESTAURANTEAPISECRET: ${RESTAURANTEAPISECRET}

  dbrestauranteapi:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}